apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp2
spec:
  replicas: 5  # 定义5个副本
  strategy:  # 定义升级策略
    canary:   # 金丝雀发布
      steps:  # 发布的节奏
      - setWeight: 20
      - pause: {}  # 会一直暂停
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2  # 下面部分其实是和 Deployment 兼容的
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: rollouts-demo
        image: registry.cn-shanghai.aliyuncs.com/public-namespace/myapp:v1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
 
---
# basic-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32070
  selector:
    app: myapp2
